config/routes.rb
CucHof::Application.routes.draw do |map|
  
  resources :polls, :only => [:index, :show, :edit, :update] do
    collection do
      get :ongoing
      get :upcoming
    end
    resources :outfits do
      member do
        post :vote_up
      end
    end
  end

  devise_for :users
  
  resources :members, :only => [:index, :show]
  

  
  root :to => "static_pages#home"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  
  belongs_to :uploader, :class_name => 'User'
  
  belongs_to :poll
  
  has_many :votes
  
  validates_presence_of :image_url
  validates_format_of :image_url, :with => URI::regexp(%w(http https))
  
  validates_presence_of :member_name
  
  attr_accessible :image_url, :member_id, :member_name, :title
  
  
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  
  before_filter :set_poll_or_redirect
  
  # GET /outfits
  # GET /outfits.xml
  def index
    @outfits = Outfit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @outfits }
    end
  end

  # GET /outfits/1
  # GET /outfits/1.xml
  def show
    @outfit = Outfit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @outfit }
    end
  end
  
  def vote_up
    @outfit = Outfit.find(params[:id])
    if(current_user.vote_for(@outfit))
      redirect_to(@outfit.poll, :success => 'Votre vote a ete enregistre !')
    else
      redirect_to(@outfit.poll, :success => 'Ooops ...')
    end
  end

  # GET /outfits/new
  # GET /outfits/new.xml
  def new
    @outfit = Outfit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @outfit }
    end
  end

  # GET /outfits/1/edit
  def edit
    @outfit = Outfit.find(params[:id])
  end

  # POST /outfits
  # POST /outfits.xml
  def create
    @outfit = @poll.outfits.new(params[:outfit])

    respond_to do |format|
      if @outfit.save
        format.html { redirect_to(upcoming_polls_path, :notice => 'Outfit was successfully created.') }
        format.xml  { render :xml => @outfit, :status => :created, :location => @outfit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @outfit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /outfits/1
  # PUT /outfits/1.xml
  def update
    @outfit = Outfit.find(params[:id])

    respond_to do |format|
      if @outfit.update_attributes(params[:outfit])
        format.html { redirect_to(@outfit, :notice => 'Outfit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @outfit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /outfits/1
  # DELETE /outfits/1.xml
  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy

    respond_to do |format|
      format.html { redirect_to(outfits_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  def set_poll_or_redirect
    @poll = Poll.find(params[:poll_id]) || redirect_to(root_url)
  end
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_form.html.erb
<% semantic_form_for([@poll, @outfit]) do |f| %>
  <%= f.input :image_url %>
  <%= f.input :title %>
  <%= f.input :member_name %>
  <% f.buttons do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/outfits/edit.html.erb
<h1>Editing outfit</h1>

<%= render 'form' %>

<%= link_to 'Show', @outfit %> |
<%= link_to 'Back', outfits_path %>

app/views/outfits/index.html.erb
<h1>Listing outfits</h1>

<table>
  <tr>
    <th>User</th>
    <th>Title</th>
    <th>Member name</th>
    <th>Image url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outfits.each do |outfit| %>
  <tr>
    <td><%= outfit.user_id %></td>
    <td><%= outfit.title %></td>
    <td><%= outfit.member_name %></td>
    <td><%= outfit.image_url %></td>
    <td><%= link_to 'Show', outfit %></td>
    <td><%= link_to 'Edit', edit_outfit_path(outfit) %></td>
    <td><%= link_to 'Destroy', outfit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Outfit', new_poll_outfit_path %>

app/views/outfits/new.html.erb
<h1>Ajouter une tenue</h1>

<%= render 'form' %>

<%= link_to 'Retour', :back %>

app/views/outfits/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @outfit.user_id %>
</p>

<p>
  <b>Title:</b>
  <%= @outfit.title %>
</p>

<p>
  <b>Member name:</b>
  <%= @outfit.member_name %>
</p>

<p>
  <b>Image url:</b>
  <%= @outfit.image_url %>
</p>


<%= link_to 'Edit', edit_outfit_path(@outfit) %> |
<%= link_to 'Back', outfits_path %>