config/routes.rb
CucHof::Application.routes.draw do |map|
  
  resources :polls, :only => [:index, :show, :edit, :update] do
    collection do
      get :ongoing
      get :upcoming
    end
    resources :outfits do
      member do
        post :vote_up
      end
    end
  end

  devise_for :users
  
  resources :members, :only => [:index, :show]
  

  
  root :to => "static_pages#home"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates_presence_of :start
  validates_presence_of :end
  
  has_many :outfits, :dependent => :destroy
  
  scope :pending, where(:state => 'pending')
  scope :ongoing, where(:state => 'ongoing')
  scope :closed, where(:state => 'closed')
  
  POLL_PERIOD = 1.month
  
  state_machine :state, :initial => :pending do
    event :open do
      transition :pending => :ongoing
    end
    
    event :close do
      transition :ongoing => :closed
    end
    
    state :ongoing
    state :closed
    state :pending
  end
  
  def after_initialize
    self.start ||= self.next_poll_start_time + 1.month # Poll will be open starting a month from now
    self.end ||= self.start + 1.month # for 1 month
  end
  
  def after_create
    #self.rotate_polls
  end
  
  def self.rotate_polls
    self.close_ongoing_polls
    self.open_pending_polls
  end
  
  
  def self.next_poll_start_time
    #end of current
  end
  
  private
  # if needed, closes current poll and opens a new one
  def self.close_ongoing_polls
    self.ongoing.where('end <=', Time.now).each do |poll|
      poll.close
    end
  end
  
  def self.open_pending_polls
    self.pending.where('start <=', Time.now).each do |poll|
      poll.open
    end
  end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  # GET /polls
  # GET /polls.xml
  def index
    @polls = Poll.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @polls }
    end
  end

  # GET /polls/1
  # GET /polls/1.xml
  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @poll }
    end
  end

  # GET /polls/1/edit
  def edit
    @poll = Poll.find(params[:id])
  end

  # PUT /polls/1
  # PUT /polls/1.xml
  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to(@poll, :notice => 'Poll was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @poll.errors, :status => :unprocessable_entity }
      end
    end
  end

  def upcoming
    @poll = Poll.pending.first
    render :show
  end
  
  def ongoing
    @poll = Poll.ongoing.first
    render :show
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= semantic_form_for(@poll) do |f| %>

  <%= f.input :start, :value => Time.now%>
  <%= f.input :end %>
  <%= f.input :title %>
  <% f.buttons do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/polls/edit.html.erb
<h1>Editing poll</h1>

<%= render 'form' %>

<%= link_to 'Show', @poll %> |
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<h1>Listing polls</h1>

<table>
  <tr>
    <th>Start</th>
    <th>End</th>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @polls.each do |poll| %>
  <tr>
    <td><%= poll.start %></td>
    <td><%= poll.end %></td>
    <td><%= poll.title %></td>
    <td><%= link_to 'Show', poll %></td>
    <td><%= link_to 'Edit', edit_poll_path(poll) %></td>
    <td><%= link_to 'Destroy', poll, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/polls/new.html.erb
<h1>New poll</h1>

<%= render 'form' %>

<%= link_to 'Back', polls_path %>

app/views/polls/show.html.erb
<% if @poll.pending? %>
<p>
  <b>Ce vote débutera le:</b>
  <%= @poll.start %>
</p>
<% elsif @poll.ongoing? %>
<p>
  <b>Ce vote se terminera le:</b>
  <%= @poll.end %>
</p>
<% else %>
<p>
  <b>Ce vote s'est terminé le:</b>
  <%= @poll.end %>
</p>
<% end %>

<h3>Tenues proposées :</h3>
<div id="outfits">
<% @poll.outfits.each do |outfit| %>
<div class="outfit">
  <%= image_tag(outfit.image_url, :width => '200px')%>
  <br />
  <span class="author"><%= outfit.member_name %></span>
  <%= button_to "Voter pour cette tenue", vote_up_poll_outfit_path(@poll, outfit) %>
</div>
<% end %>
<%= link_to 'Proposer une tenue', new_poll_outfit_path(@poll) %>